# The Trusty beta Build Environment
sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools libqt5websockets5-dev  #install necessary Qt files

script:
  - cd FishServ
  - qmake
  - make
  - cd ../FishCli
  - qmake 
  - make 
